### ISSUE TITLE
Suggestion: Hide popup by clicking when it is open.

### ISSUE THREAD

**Issue by eltonfabricio10** [halfbrained/cuda_breadcrumbs#25]
If that's not difficult...

**Comment by Alexey-T** [comment]
By clicking outside of popup?

**Comment by JairoMartinezA** [comment]
Yes after click on Editor auto-close dialog.

**Comment by Alexey-T** [comment]
what is 'Editor auto-close dialog'?

**Comment by JairoMartinezA** [comment]
I can see that the dialog is opened as a Modal dialog because it don't allows any interaction with the rest of CudaText until the user press Esc. The idea is to make the dialog as responsive in order to close when it lose the focus.
![LostFocus](https://user-images.githubusercontent.com/5806694/124656267-930c0100-de66-11eb-828c-4f719438a6df.gif)

**Comment by eltonfabricio10** [comment]
> By clicking outside of popup?

Nope!
By clicking on highlighted breadcrumbs

**Comment by halfbrained** [comment]
Oh, right, on windows `dlg_proc` dialogs are really modal :)

**Comment by halfbrained** [comment]
Should hide now

**Comment by Alexey-T** [comment]
seems good now.
